project:
  type: manuscript

bibliography: references.bib
cache: true
citation: true
df-print: kable
fig-align: center
fig-dpi: 600
lang: en
lightbox: true
link-external-newwindow: true
number-sections: true

format:
  html:
    theme: zephyr
    html-math-method: katex
    css: styles.css
    fig-format: jpeg
    include-in-header:
      text: |
        <script defer data-domain="camillemondon.com" src="https://analytics.mndn.fr/js/script.js"></script>
  arxiv-pdf:
    authorcols: true
    biblatexoptions:
      - style=authoryear
      - backend=biber
      - backref=true
    cite-method: biblatex
    colorlinks: false
    fig-format: pdf
    fig-pos: ht
    link-citations: true
    notebook-links: false
    pdf-engine: pdflatex
