# Conclusion and perspectives {#sec-conclusion}

We propose a coordinate-free presentation of ICS that allows ICS to be
applied to more complex objects than the coordinates vectors of
multivariate analysis. We focus on the case of distributional data and
describe an outlier detection procedure based on ICS. However, one of
the limitations of the coordinate-free approach is that it is mainly
adapted to pairs of weighted covariance operators, because they have a
coordinate-free definition. These pairs of operators include the
well-known $(\operatorname{Cov}, \operatorname{Cov}_4)$ pair. Its
scatter counterpart in the multivariate context is the one recommended
by @archimbaud_detection_2018 for a small proportion of outliers. But it
is unclear how we could generalise other well-known scatter matrices
(such as M-estimators, pairwise-based weighted estimators, or Minimum
Covariance Determinant estimators) which are useful when using ICS as a
preprocessing step for clustering [see @alfons_tandem_2024].

Concerning a further adaptation of ICSOutlier to density objects, one
perspective to our work is to take into account different settings for
the preprocessing parameters and aggregate the results in a single
outlyingness index. Another perspective is to consider multivariate
densities (e.g., not only maximum density temperature but also minimum
density temperature, precipitation,...) and generalise the ICSOutlier
procedure as in [@archimbaud_ics_2022] for multivariate functional data.

This coordinate-free framework for ICS lays the groundwork for a
generalisation to infinite-dimensional Hilbert spaces. Many difficulties
arise, such as the compactness of the covariance operator which makes it
non surjective, so that one cannot easily define a Mahalanobis distance,
on which our definition of weighted covariance operators relies.
Moreover, the existence of solutions and other properties of ICS proved
in this paper come from the fact that one of the scatter operators is an
automorphism, so it cannot be compact (in particular not the
covariance). Finally, @tyler_note_2010 proved that, whenever the
dimension $p$ is larger than the number of observations $n$, all affine
equivariant scatter operators are proportional, which is a bad omen for
a straight generalisation to infinite-dimensional Hilbert spaces. One
can partially circumvent these difficulties by assuming that the data is
almost surely in a deterministic finite-dimensional subspace $E$ of $H$
(which is the case for density data after our preprocessing) and
applying coordinate-free ICS. Another option could be to alleviate the
affine equivariance assumption.
