## Scatter operators for random objects in a Hilbert space {.appendix .unnumbered}

Let us first discuss some definitions relative to scatter operators in
the framework of a Hilbert space $(E, \langle \cdot, \cdot \rangle)$. We
consider an $E$-valued random object $X: \Omega \rightarrow E$ where
$\Omega$ is a probability space and $E$ is a Hilbert space equipped with
the Borel $\sigma$-algebra. In order to define ICS, we need at least two
scatter operators, which generalise the covariance operator defined on
$E$ by
$$\forall (x,y) \in E^2, \langle \operatorname{Cov} [X] x, y \rangle = \mathbb E \left[ \langle X - \mathbb EX, x \rangle \langle X - \mathbb EX, y \rangle \right],$${#eq-cov}
while keeping its affine equivariance property:
$$\forall A \in \mathcal{GL} (E), \forall b \in E, \operatorname{Cov} [AX+b] = A \operatorname{Cov} [X] A^*,$$
where the Hilbert norm of $X$ is assumed to be square-integrable, and
$A^*$ is the adjoint linear operator of $A$ in the Hilbert space $E$,
represented by the transpose of the matrix that represents $A$.

::: {#def-scatter}
# Scatter operators
Let $(E, \langle \cdot, \cdot \rangle)$ be a Hilbert space of dimension $p$,
$\mathcal E$ an affine invariant set of $E$-valued random objects,
i.e. that verifies:
$$\forall X \in \mathcal E, \forall A \in \mathcal{GL} (E), \forall b \in E, AX+b \in \mathcal E.$${#eq-affine-inv-set}
An operator $S: \mathcal E \rightarrow \mathcal S^+ (E)$ (where
$\mathcal S^+ (E)$ is the space of non-negative symmetric operators on
$E$) is called an (affine equivariant) scatter operator (defined on
$\mathcal E$) if it satisfies the following two properties:

1.  Invariance by equality in distribution:
    $$\forall (X,Y) \in \mathcal E^2, X \sim Y \Rightarrow S[X] = S[Y].$$

2.  Affine equivariance:
    $$\forall X \in \mathcal E, \forall A \in \mathcal{GL} (E), \forall b \in E, S[AX+b] = A S[X] A^*.$$
:::

We do not know whether there exist other scatter operators than the
covariance when the Hilbert space has infinite dimension.

## Details on coordinate-free ICS {.appendix .unnumbered}

The problem $\operatorname{ICS} (X, S_1, S_2)$ defined by
@eq-icsdef is equivalent to assuming that $S_1 [X]$ is
injective and finding an orthonormal basis $H$ that diagonalises the
non-negative symmetric operator $S_1 [X]^{-1} S_2 [X]$ in the Euclidean
space $(E, \langle S_1[X] \cdot, \cdot \rangle)$. The
$\operatorname{ICS} (X,{S_1},{S_2})$ spectrum $\Lambda$ is unique and is
simply the spectrum of $S_1 [X]^{-1} S_2 [X]$.

::: {#prp-existence}
# Existence of solutions
Let $(E, \langle \cdot, \cdot \rangle)$ be a Euclidean space of dimension
$p$, $\mathcal E \subseteq L^1 (\Omega, E)$ an affine invariant set of
integrable $E$-valued random objects, $S_1$ and $S_2$ two scatter
operators on $\mathcal E$. For any $X \in \mathcal E$ such that
$S_1 [X]$ is an automorphism, there exists at least one solution
$(H, \Lambda)$ to the problem $\operatorname{ICS}(X, S_1, S_2)$, and
$\Lambda$ is a uniquely determined non-increasing sequence of positive
real numbers.
:::

::: {.proof}
Since $S_1 [X]$ is non-singular, $S_1 [X]^{-1} S_2 [X]$ exists
and is symmetric in the Euclidean space
$(E, \langle {S_1}[X] \cdot, \cdot \rangle)$, because $$\begin{aligned}
\forall (x,y) \in E^2, \langle S_1[X]  S_1 [X]^{-1} S_2 [X] x, y \rangle &= \langle S_2 [X]x, y \rangle = \langle S_2 [X] y, x \rangle \\
&= \langle S_1[X] S_1 [X]^{-1} S_2 [X] y, x \rangle.
\end{aligned}$$ Thus, the spectral theorem guarantees that there exists
an orthonormal basis $H$ of $(E, \langle {S_1}[X] \cdot, \cdot \rangle)$
in which $S_1 [X]^{-1} S_2[X]$ is diagonal. 
:::

This methodology does not generalise to the infinite-dimensional case,
because the inner product space
$(\mathcal H, \langle \cdot, S_1 [X] \cdot \rangle)$ is not necessarily
complete, so the spectral theorem does not apply.

::: {.remark}
# Courant-Fischer variational principle
The ICS problem @eq-icsdef can be stated as a maximisation problem. If
$1 \leq j \leq p$, the following equalities hold:
$$h_j \in \underset{h \in E, \langle S_1 [X] h, h_{j'} \rangle = 0 \text{ if } 0 < j' < j}{\operatorname{argmax}} \frac{\langle{S_2} [X] h, h \rangle}{\langle{S_1} [X] h, h \rangle} \;\text{ and }\;
\lambda_j = \max_{h \in E, \langle S_1 [X] h, h_{j'} \rangle = 0 \text { if } 0 < j' < j} \frac{\langle{S_2} [X] h, h \rangle}{\langle{S_1} [X] h, h \rangle}.$${#eq-Courant}
:::

The following reconstruction formula, extended from multivariate to
complex data, is useful to interpret the ICS dual eigenbasis
$H^* = (h^*_j)_{1 \leq j \leq p}$, which is defined as the only basis of
the space $E$ that satisfies
$$\langle h_j, h^*_{j'} \rangle = \delta_{jj'} \text{ for all }1 \leq j, j' \leq p.$$

::: {#prp-reconstruction}
# Reconstruction formula
Let $(E, \langle \cdot, \cdot \rangle)$ be a Euclidean space of dimension
$p$, $\mathcal E \subseteq L^1 (\Omega, E)$ an affine invariant set of
integrable $E$-valued random objects, $S_1$ and $S_2$ two scatter
operators on $\mathcal E$. For any $X \in \mathcal E$ such that
$S_1 [X]$ is an automorphism and any $\operatorname{ICS}(X, S_1, S_2)$
eigenbasis ${H} = (h_1, \dots, h_p)$ of $E$, we have
$$X = \mathbb EX + \sum_{j=1}^p z_j h^*_j,$$ where the
$z_j, 1 \leq j \leq p$ are defined as in
@eq-ic and
$H^* = (h^*_j)_{1 \leq j \leq p} = ({S_1} [X] h_j)_{1 \leq j \leq p}$ is
the dual basis of $H$.
:::

## Reminder on Bayes spaces {.appendix .unnumbered}

The most recent and complete description of the Bayes spaces approach
can be found in [@van_den_boogaart_bayes_2014]. For the present work, we
will identify the elements of a Bayes space, as defined by
@van_den_boogaart_bayes_2014, with their Radon--Nikodym derivative with
respect to a reference measure $\lambda$. This leads to the following
framework: let $(a,b)$ be a given interval of the real line equipped
with the Borel $\sigma$-algebra, let $\lambda$ be a finite reference
measure on $(a,b)$. Let $B^2(a,b)$ be the space of square-log integrable
probability densities $\frac{d\mu}{d\lambda},$ where $\mu$ is a measure
that is equivalent to $\lambda$, which means that $\mu$ and $\lambda$
are absolutely continuous with respect to each other.

Note that the simplex $\mathcal S^p$ used in compositional data analysis
can be seen as a Bayes space when considering, instead of an interval
$(a,b)$ equipped with the Lebesgue measure, the finite set
$\{1, \dots, p+1\}$ equipped with the counting measure [see Example 2 in
@van_den_boogaart_bayes_2014].

Let us first briefly recall the construction of the Hilbert space
structure of $B^2(a,b)$. For a density $f$ in $B^2(a,b)$, the clr
transformation is defined by
$$\operatorname{clr} f(.) = \log f(.) - \frac{1}{\lambda(a,b)}\int_{a}^{b}\log
    f(t)d\lambda(t).$$ The clr transformation maps an element of
$B^2(a,b)$ into an element of the space $L^2_0(a,b)$ of functions which
are square-integrable with respect to $\lambda$ on $(a,b)$ and whose
integral is equal to zero. The clr inverse of a function $u$ of
$L^2_0(a,b)$ is ${B}^2$-equivalent to $\exp(u).$ More precisely, if
$u \in L^2_0 (a,b),$
$$\operatorname{clr}^{-1}(u)(.) = \frac{\exp u(.)}{\int_a^b \exp{u(t)  d\lambda(t)}}.$$
A vector space structure on $B^2(a,b)$ is readily obtained by
transporting the vector space structure of $L^2_0 (a,b)$ to $B^2(a,b)$
using the clr transformation and its inverse, see for example
@van_den_boogaart_bayes_2014. Its operations, denoted by $\oplus$ and
$\odot$, are called perturbation (the "addition") and powering (the
"scalar multiplication").

For the definition of the inner product, we adopt a normalization
different from that of @egozcue_hilbert_2006 and of
@van_den_boogaart_bayes_2014 in the sense that we choose the classical
definition of inner product in $L^2_0(a,b),$ for two functions $u$ and
$v$ in $L^2_0 (a,b)$
$$\langle u,v \rangle_{L^2_0} = \int_a^b u(t)v(t)d\lambda(t),$${#eq-inner} so
that the corresponding inner product between two densities $f$ and $g$
in the Bayes space $B^2(a,b)$ is given by
$$\langle f ,g \rangle_{B^2} = \frac{1}{2 \lambda(a,b)}\int_a^b \int_a^b 
    (\log f(t) - \log f(s))
    (\log g(t) - \log g(s))
    d \lambda(t)d \lambda(s).$${#eq-innerpdt}
This normalization yields an inner
product which is homogeneous to the measure $\lambda$ whereas the
@van_den_boogaart_bayes_2014 normalization is unitless. Note that, for
clarity and improved readability, the interval over which the spaces
$L^2_0$ and $B^2$ are defined are omitted from some notations.

For a random density $f(.)$ in the infinite-dimensional space
${B}^2(a,b)$, the expectation and covariance operators can be defined as
follows, whenever they exist: $$\begin{aligned}
\mathbb{E}^{B^2} [ f ] &=& \operatorname{clr}^{-1} \mathbb{E} [ \operatorname{clr} f] \in {B}^2 (a,b) \\
\operatorname{Cov}^{B^2} [f] g &=& \mathbb{E}^{B^2} \left[ \langle f \ominus \mathbb{E}^{B^2} [ f ], g \rangle_{B^2} \odot ( f \ominus \mathbb{E}^{B^2} [ f ]) \right] \nonumber \\
&=& \operatorname{clr}^{-1}\mathbb{E} [ \langle f, g \rangle_{B^2} \operatorname{clr}f ]  \nonumber \\
&=& \operatorname{clr}^{-1}\mathbb{E} [ \langle \operatorname{clr}f, \operatorname{clr} g \rangle_{{ L}^2_0} \operatorname{clr}f ] \quad \text{ for any } g \in B^2(a,b),
\end{aligned}$${#eq-covw2} where $\ominus$ is the negative perturbation defined by
$f \ominus g = f \oplus [(-1) \odot g]$.

## Reminder on compositional splines {.appendix .unnumbered}

Following [@machalova_compositional_2021], in order to construct a basis
of $E = \mathcal C^{\Delta \gamma}_d (a,b)$, which is required in
practice, it is convenient to first construct a basis of a
finite-dimensional spline subspace of $L^2_0(a,b)$, which we then
transfer to $B^2(a,b)$ by the inverse $\operatorname{clr}$
transformation. More precisely, @machalova_preprocessing_2016 propose a
basis of zero-integral splines in $L^2_0(a,b)$ that are called
ZB-splines. The corresponding inverse images of these basis functions by
clr are called CB-splines.

A ZB-spline basis, denoted by $Z = \{Z_1, \ldots, Z_{k+d-1}\},$ is
characterised by the spline of degree less than or equal to $d$ (order
$d+1$), the number $k$ and the positions of the so-called inside knots
$\Delta \gamma = \{ \gamma_1, \ldots, \gamma_d\}$ in $(a,b)$. The
dimension of the resulting subspace ${\cal Z}_d^{\Delta \gamma}$ is
$p=k+d$. Let ${\cal C}_d^{\Delta \gamma}$ be the subspace generated by
$C=\{C_1, \ldots, C_p\}$ in $B^2(a,b)$, where
$C_j = \operatorname{clr}^{-1}(Z_j)$ are the back-transforms in
$B^2(a,b)$ of the basis functions of the subspace
${\cal Z}_d^{\Delta \gamma}$. The expansion of a density $f$ in
$B^2(a,b)$ is then given by
$$f(t) = \bigoplus_{j=1}^p [f]_{C_j} C_j(t),$${#eq-expan_B2}
so that the corresponding
expansion of its $\operatorname{clr}$ in $L^2_0(a,b)$ is given by
$$\operatorname{clr} f(t) = \sum_{j=1}^p [f]_{C_j} Z_j(t).$${#eq-expan_L2}

Note that the coordinates of $f$ in the basis $C$ are the same as the
coordinates of $\operatorname{clr}(f)$ in the basis $Z$, for
$j=1, \ldots, p, [f]_{C_j} = [\operatorname{clr} f]_{Z_j}.$ Following
@machalova_preprocessing_2016, the basis functions of
${\cal Z}_d^{\Delta \gamma}$ can be written in a B-spline basis, see
@schumaker_spline_1981, which is convenient to allow using existing code
for their computation.

## Proofs {.appendix .unnumbered}

::: {.proof}
# @prp-isometry
First, let us verify that the problem
$\operatorname{ICS} (X^{\mathcal F}, S_1^{\mathcal F}, S_2^{\mathcal F})$
is well defined on $F$:

(a) The application $\varphi$ is linear so it is measurable. Moreover,
    if $X \in \mathcal E$, $A \in \mathcal{GL} (F)$ and $b \in F$, then
    $$\|\varphi(X)\|_F = \| X \|_E$$ and
    $$A \varphi(X) + b = \varphi \left( \varphi^{-1} \circ A \circ \varphi (X) + \varphi^{-1}(b) \right) \text{ where } \varphi^{-1} \circ A \circ \varphi (X) + \varphi^{-1}(b) \in \mathcal E.$$

(b) If $X \in \mathcal E$,
    $S_\ell^{\mathcal F} [\varphi (X)] = \varphi \circ S_\ell^{\mathcal E} [X] \circ \varphi^{-1}$
    is a non-negative symmetric operator and if $Y \in \mathcal E$
    verifies $\varphi (X) \sim \varphi (Y)$, then $X \sim Y$ (because
    the Borel $\sigma$-algebra on $E$ is the pullback by $\varphi$ of
    that on $F$) so that, for $\ell \in \{ 1, 2 \}$,
    $$S_\ell^{\mathcal F} [\varphi (X)] = \varphi \circ S_\ell^{\mathcal E} [X] \circ \varphi^{-1} = \varphi \circ S_\ell^{\mathcal E} [Y] \circ \varphi^{-1} = S_\ell^{\mathcal F} [\varphi (Y)]$$
    and $$\begin{gathered}
            S_\ell^{\mathcal F} [A \varphi(X) + b]
            = \varphi \circ S_\ell^{\mathcal E} [\varphi^{-1} \circ A \circ \varphi (X) + \varphi^{-1}(b)] \circ \varphi^{-1} \\
            = A \circ \varphi \circ S_\ell^{\mathcal E} [X] \circ \varphi^{-1} \circ A^*
            = A S_\ell^{\mathcal F} [\varphi(X)] A^*.
    \end{gathered}$$

(c) The isometry $\varphi$ preserves the linear rank of any finite
    sequence of vectors of $E$.

Now, $(H^{\mathcal E}, \Lambda)$ solves
$\operatorname{ICS} (X^{\mathcal E}, S_1^{\mathcal E}, S_2^{\mathcal E})$
in the space $E$ if and only if $$\begin{aligned}
    &\left\{
    \begin{aligned}
        \langle S_1^{\mathcal E} [X] h_j^{\mathcal E}, h_{j'}^{\mathcal E} \rangle_E &= \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p  \\
        \langle S_2^{\mathcal E} [X] h_j^{\mathcal E}, h_{j'}^{\mathcal E} \rangle_E &= \lambda_j \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p 
    \end{aligned}
    \right. \\
    \iff &\left\{
    \begin{aligned}
        \langle \varphi (S_1^{\mathcal E} [X] h_j^{\mathcal E}), \varphi (h_{j'}^{\mathcal E}) \rangle_F &= \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p  \\
        \langle \varphi (S_2^{\mathcal E} [X] h_j^{\mathcal E}), \varphi (h_{j'}^{\mathcal E}) \rangle_F &= \lambda_j \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p 
    \end{aligned}
    \right. \\
    \iff &\left\{
    \begin{aligned}
        \langle S_1^{\mathcal F} [X] h_j^{\mathcal F}, h_{j'}^{\mathcal F} \rangle_F &= \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p  \\
        \langle S_2^{\mathcal F} [X] h_j^{\mathcal F}, h_{j'}^{\mathcal F} \rangle_F &= \lambda_j \delta_{jj'} \text{ for all } 1 \leq j, j' \leq p,
    \end{aligned}
    \right.
\end{aligned}$$ which is equivalent to the fact that
$(H^{\mathcal F}, \Lambda)$ solves
$\operatorname{ICS} (X^{\mathcal F}, S_1^{\mathcal F}, S_2^{\mathcal F})$
in the space $F$. 
:::

::: {.proof}
# @cor-isometry-covw
Let $\ell \in \{ 1, 2 \}$ and $\tilde X = X - \mathbb EX$. In order to prove the equation
@eq-isometry-covw, we will need to prove that, for any
$(x,y) \in F^2$, $$\begin{aligned}
    \langle \varphi \circ \operatorname{Cov}_{w_\ell}^E [X] \circ \varphi^{-1} (x), y \rangle_F
    &= \langle \operatorname{Cov}_{w_\ell}^E [X] \varphi^{-1} (x), \varphi^{-1} (y) \rangle_E \\
    &= \mathbb E [ w_\ell (\| \operatorname{Cov}^E [X]^{-1/2} \tilde X \|_E)^2 \langle \tilde X, \varphi^{-1} (x) \rangle_E \langle \tilde X, \varphi^{-1} (y) \rangle_E ] \\
    &= \mathbb E [ w_\ell (\| \operatorname{Cov}^F [\varphi(X)]^{-1/2} \varphi(\tilde X) \|_F)^2 \langle \varphi(\tilde X), x \rangle_F \langle \varphi(\tilde X), y \rangle_F ]  \\
    \langle \varphi \circ \operatorname{Cov}_{w_\ell}^E [X] \circ \varphi^{-1} (x), y \rangle_F
    &= \langle \operatorname{Cov}_{w_\ell}^F [\varphi(X)] x, y \rangle_F.
\end{aligned}$${#eq-cor-isometry-covw} It is enough to show the equality between
@eq-cor-isometry-covw (2) and
@eq-cor-isometry-covw (3), for which we treat differently the
cases $w_\ell = 1$ and $w_\ell \neq 1$. If $w_\ell = 1$, there is
nothing to prove, so that the equation
@eq-isometry-covw holds for the covariance operator. If
$w_\ell \neq 1$, we now know from the case $w_\ell = 1$ that
$$\operatorname{Cov}^F [\varphi(X)]^{-1/2} = \varphi \circ \operatorname{Cov}^E [X]^{-1/2} \circ \varphi^{-1}$$
so that
$$\| \operatorname{Cov}^E [X]^{-1/2} \tilde X \|_E
    = \| \operatorname{Cov}^F [\varphi(X)]^{-1/2} \varphi(\tilde X) \|_F$${#eq-isometry-mahalanobis}
Once the equation
@eq-isometry-covw is proved, one only needs to apply
@prp-isometry to finish the proof. 
:::

::: {.proof}
# @cor-coord
Applying @cor-isometry-covw to the isometry
$$\varphi_B: \left\{\begin{array}{ccc}
        (E, \langle \cdot, \cdot \rangle_E) &\rightarrow& (\mathbb R^p, \langle \cdot, \cdot \rangle_{\mathbb R^p}) \\
        x &\mapsto& G_B^{1/2} [x]_B,
    \end{array}\right.$$ we obtain the equivalence between the following
assertions:

(i) $(H, \Lambda)$ solves
    $\operatorname{ICS} (X, \operatorname{Cov}_{w_1}, \operatorname{Cov}_{w_2})$
    in the space $E$

(ii) $(G_B^{1/2} [H]_B, \Lambda)$ solves
     $\operatorname{ICS} (G_B^{1/2} [X]_B, \operatorname{Cov}_{w_1}, \operatorname{Cov}_{w_2})$
     in the space $\mathbb R^p$,

which gives the equivalence between the assertions (1) and (2). The
equivalence between the other assertions are deduced from the fact that
for any $\ell \in \{ 1, 2 \}$ and any $(x,y) \in E^2$: $$\begin{aligned}
\langle \operatorname{Cov}_{w_\ell}^E [X] x, y \rangle_E
&= \langle \operatorname{Cov}_{w_\ell} (G_B^{1/2} [X]_B) G_B^{1/2} [x]_B, G_B^{1/2} [y]_B \rangle_{\mathbb R^p} \\
&= \langle \operatorname{Cov}_{w_\ell} (G_B [X]_B) [x]_B, [y]_B \rangle_{\mathbb R^p} \\
&= \langle \operatorname{Cov}_{w_\ell} ([X]_B) G_B [x]_B, G_B [y]_B \rangle_{\mathbb R^p},
\end{aligned}$${#eq-cor-coord} where
@eq-cor-coord (1) comes from the equation
@eq-isometry-covw, and the equalities
@eq-cor-coord (2) and
@eq-cor-coord (3) come from the affine equivariance of
$\operatorname{Cov}_{w_\ell}$. 
:::

::: {.proof}
# @prp-reconstruction
Let us decompose $S_1[X]^{-1} (X - \mathbb EX)$ over the basis $H$, which is orthonormal
in $(E, \langle \cdot, S_1[X] \cdot \rangle)$: $$\begin{aligned}
S_1[X]^{-1} (X - \mathbb EX)
&= \sum_{j=1}^p \langle S_1[X]^{-1} (X - \mathbb EX), S_1[X] h_j \rangle h_j \\
&= \sum_{j=1}^p \langle X - \mathbb EX, h_j \rangle h_j \\
S_1[X]^{-1} (X - \mathbb EX)
&= \sum_{j=1}^p z_j h_j.
\end{aligned}$$ The dual basis $H^*$ of $H$ is the one that satisfies
$\langle h_j, h^*_{j'} \rangle = \delta_{jj'}$ for all
$1 \leq j, j' \leq p$ and we know from the definition of ICS that this
holds for $(S_1[X] h_j)_{1 \leq j \leq p}$. 
:::

## Code & reproducibility {.appendix .unnumbered}

In order to implement coordinate-free ICS, we created the R package
`ICSFun`, which is used to generate the figures
(see the code in this HTML version of the article).
